#!/bin/sh

### Check for errors; abandon the process if error exist
function checkError {
    COLOR='\033[01;31m'    # bold red
    RESET='\033[00;00m'    # normal white

    if [[ $1 != 0 ]] ; then
        echo "${COLOR}An error has been encountered. Aborting GIT PUSH.${RESET}"

        #prevent commit with error code
        exit 99
    fi
}

echo "*** RUNNING TESTS..."
jest
checkError $?

exit 0